general:
  seed: 42
  use_bert: False
  schema: True
  pretraining: False
  use_bm25: False
  use_hnbm25: False

# This config is based on the initial parameters and decisions made
# by the original authors
conversion:
  input_interactions_dir: ../data/interactions
  input_tables_dir: ../data/tables
  output_dir: ../data/tf_examples
  vocab_file: ../data/vocab.txt
  max_seq_length: 512
  max_column_id: 512
  max_row_id: 512
  cell_trim_length: -1
  use_document_title: True
  converter_impl: PYTHON
  
bm25: 
  interaction_files: ["../data/tf_examples/dev.tfrecord"]
  table_file: ""
  max_table_rank: 50
  min_term_rank: 100
  drop_term_frequency: True

