# This config is based on the initial parameters and decisions made
# by the original authors
# It is used for data conversion
base:
  input_interactions_dir: ../data/interactions
  input_tables_dir: ../data/tables
  output_dir: ../data/tf_examples
  vocab_file: ../data/vocab.txt
  max_seq_length: 512
  max_column_id: 512
  max_row_id: 512
  cell_trim_length: -1 # If > 0: Trim cells so that the length is <= this value
  use_document_title: True
  converter_impl: PYTHON