# This config is for the retrieval result evaluation
# (which also generates the KNN files needed for reader experiments)
base:
  prediction_files_local: /home/scur2840/IR2-stefan/outputs/predict_results_test.tsv
  prediction_files_global: /home/scur2840/IR2-stefan/outputs/predict_results_tables.tsv
  retrieval_results_file_path: /home/scur2840/IR2-stefan/outputs/knn/test_knn.jsonl