# This config is the version used in the notebook
base:
  data_format: tfrecord
  input_file_train: null
  input_file_eval: nq-tables/tf_examples/nq_table.tfrecord 
  input_file_predict: nq-tables/tf_examples/nq_tables_interactions_test.tfrecord
  model_dir: tapas_dual_encoder_proj_256_large  # Be sure to change this to the model you want to evaluate
  prediction_output_dir: outputs/
  init_checkpoint: null
  max_seq_length: 512
  minutes_to_sleep_before_predictions: 0
  do_train: false
  do_eval: false
  do_predict: true
  eval_name: retrieval_predict
  grad_clipping: null
  down_projection_dim: 256
  init_from_single_encoder: false
  max_query_length: 128
  compression_type: null
  evaluated_checkpoint_step: 0
  evaluated_checkpoint_metric: null
  use_out_of_core_negatives: false
  mask_repeated_tables: false
  mask_repeated_questions: false
  ignore_table_content: false
  use_mined_negatives: false
  disabled_features: []
  learning_rate: 1.25e-5
